### ISSUE TITLE
Themes?

### ISSUE THREAD

**Issue by robsontenorio** [alenaksu/json-viewer#58]
How to properly set the theme light/dark?

I can't see on docs how to manage it.

**Comment by alenaksu** [comment]
There is not light/dark theme at the moment, even though It's something I was thinking to add.

In the meanwhile, you could define your own theme using CSS custom properties.
Please see the [documentation](https://github.com/alenaksu/json-viewer?tab=readme-ov-file#css-custom-properties).

This is an example:
```css
json-viewer {
    --background-color: #f8f8f2;
    --color: #2a2f3a;
    --string-color: #a11;
    --number-color: #164;
    --boolean-color: #219;
    --null-color: #219;
    --property-color: #05a;
    --preview-color: rgb(209 123 64 / 90%);
    --highlight-color: #c50b0b;
    --outline-color: #444444;
    --outline-width: 1px;
    --outline-style: dotted;
    --font-family: Nimbus Mono PS, Courier New, monospace;
    --font-size: 1rem;
    --line-height: 1.2rem;
    --indent-size: 0.5rem;
    --indentguide-size: 1px;
    --indentguide-style: solid;
    --indentguide-color: #e2e4e6;
    --indentguide-color-active: #767777;
    --indentguide: var(--indentguide-size) var(--indentguide-style) var(--indentguide-color);
    --indentguide-active: var(--indentguide-size) var(--indentguide-style) var(--indentguide-color-active);
}
```
